"""Add ON DELETE CASCADE to task_id in task_assignee_association

Revision ID: 6460df4bcb07
Revises: 1f635ac320e7
Create Date: 2025-06-17 15:24:19.237644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6460df4bcb07'
down_revision: Union[str, None] = '1f635ac320e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('task_assignee_association_task_id_fkey'), 'task_assignee_association', type_='foreignkey')
    op.create_foreign_key(None, 'task_assignee_association', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_assignee_association', type_='foreignkey')
    op.create_foreign_key(op.f('task_assignee_association_task_id_fkey'), 'task_assignee_association', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
